reset_arduino:
    ros__parameters:
        input_topic: /arduino/reset          # topic with arduino reset task
        output_topic: /arduino/reset/success # topic with true bool msg after arduino reset
        reset_pin: 18                        # rpi output pin
