drive_controller_serial:
    ros__parameters:
        port: /dev/ttyACM1                         # arduino port
        baudrate: 9600                             # baudrate for arduino
        cmd_size: 3                                # msg size from linux
        msg_size: 1                                # msg size from arduino
        receive_time: 100                          # delay after receiving msg from arduino
        pub_topic: /serial/drive_controller/pub    # topic name for arduino receiver
        sub_topic: /serial/drive_controller/sub    # topic name for arduino sender
        use_receiver: false                        # ignoring msgs from arduino if false

drive_controller:
    ros__parameters:
        input_sub: /drive_controller_input         # input topic
        serial_pub: /serial/drive_controller/pub   # topic with motors velocities values in rad/s
        serial_sub: /serial/drive_controller/sub   # topic with odometry poses in ticks and odometry velocities in rad/s
        cmd_size: 3                                # cmd size
