nav:
    ros__parameters:
        data_topic: /nav/input
        target_topic: /target
        active_topic: /nav/active
        vel_topic: /drive_controller/input
        teleop_topic: /teleop
        min_dist: 2.0
        min_angle: 5.0
